name: Emo
favicon: null
layout_spectrum: 0.50518
typography_spectrum: 0.21764
title: embedded media objects
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.506383
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
