layout_spectrum: 0.306383
typography_spectrum: 0.3808511
color:
  lightness: 0
  brandStrength: 0.506383
  saturation: 0.1531915
  rhythmicContrast: 1
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: Emo
